---
textures:
  - id: Leader
    path: Assets/Sprites/blanket.png
  - id: Fighter
    path: Assets/Sprites/Nairan/Designs-Base/PNGs/Nairan-Fighter-Base.png
  - id: FighterEffect
    path: Assets/Sprites/Nairan/Engine-Effects/PNGs/Nairan-Fighter-Engine.png
  - id: FighterWeapons
    path: Assets/Sprites/Nairan/Weapons/PNGs/Nairan-Fighter-Weapons.png
  - id: Rocket
    path: Assets/Sprites/Nairan/Weapon-Effects-Projectiles/PNGs/Nairan-Rocket.png

animations:
  - id: FighterEffectAnimation
    textureId: FighterEffect
    frames:
      - x: 0
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 64
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 128
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 192
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 256
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 320
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 384
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 448
        y: 0
        width: 64
        height: 64
        duration: 0.1
  - id: FighterWeaponsAnimation
    textureId: FighterWeapons
    frames:
      - x: 0
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 64
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 128
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 192
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 256
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 320
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 384
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 448
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 512
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 576
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 640
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 704
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 768
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 832 
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 896
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 960
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1024
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1088
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1152
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1216
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1280
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1344
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1408
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1472
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1536
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1600
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1664
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1728
        y: 0
        width: 64
        height: 64
        duration: 0.1
      - x: 1792
        y: 0
        width: 64
        height: 64
        duration: 0.1
  - id: RocketAnimation
    textureId: Rocket
    frames:
      - x: 0
        y: 0
        width: 9
        height: 16
        duration: 0.1
      - x: 9
        y: 0
        width: 9
        height: 16
        duration: 0.1
      - x: 18
        y: 0
        width: 9
        height: 16
        duration: 0.1
      - x: 27
        y: 0
        width: 9
        height: 16
        duration: 0.1